---

- include_role:
    name: httpd
  vars:
    httpd_tls: True
  tags:
    - tls

- name: Ensuring we configure max number of open files by httpd
  template:
    src: httpd-limit_nofile.conf.j2
    dest: /etc/systemd/system/httpd.service.d/httpd-limit_nofile.conf
  register: httpd_systemd_override  
  notify:
    - restart_httpd

- name: Reloading systemd if needed
  command: systemctl daemon-reload
  when: httpd_systemd_override is changed

- name: TLS certs
  copy:
    src: "{{ pkistore }}/{{ item }}"
    dest: "/etc/pki/tls/certs/{{ item }}"
  with_items:
    - "{{ pagure_public_hostname }}.crt"
    - "{{ pagure_public_hostname }}-CAChain.crt"
    - "{{ lookaside_fas_ca_crt }}"
  tags:
    - tls
  notify:
    - restart_httpd

- name: TLS keys
  copy:
    src: "{{ pkistore }}/{{ item }}"
    dest: "/etc/pki/tls/private/{{ item }}"
  with_items:
    - "{{ pagure_public_hostname }}.key"
  tags:
    - tls

- name: httpd tls vhost config
  template:
    src: "httpd-{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
  with_items:
    - ssl-pagure.conf
    - vhost-pagure.conf
    - pagure.conf
  notify:
    - restart_httpd

