---

- include_role:
    name: httpd
  vars:
    httpd_tls: True

- name: TLS certs
  copy:
    src: "{{ pkistore }}/{{ item }}"
    dest: "/etc/pki/tls/certs/{{ item }}"
  with_items:
    - "{{ pagure_public_hostname }}.crt"
    - "{{ pagure_public_hostname }}-CAChain.crt"
    - "{{ lookaside_fas_ca_crt }}"
  tags:
    - tls
  notify:
    - restart_httpd

- name: TLS keys
  copy:
    src: "{{ pkistore }}/{{ item }}"
    dest: "/etc/pki/tls/private/{{ item }}"
  with_items:
    - "{{ pagure_public_hostname }}.key"
  tags:
    - tls

- name: httpd tls vhost config
  template:
    src: "httpd-{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
  with_items:
    - ssl-pagure.conf
    - vhost-pagure.conf
    - pagure.conf
  notify:
    - restart_httpd

- name: make the lookaside cache directory
  file:
    path: "{{ lookaside_rootpath }}/lookaside"
    state: directory
    owner: apache
    group: apache
    mode: 0775
    setype: git_user_content_t

- name: Ensuring that scponly is installed for specific shell
  yum:
    name: rssh
    state: installed

- name: Ensuring some protocols are allowed through rssh
  blockinfile:
    path: /etc/rssh.conf
    block: |
      allowscp
      allowsftp
      allowrsync

- name: Default umask for rssh push
  lineinfile:
    path: /etc/rssh.conf
    regexp: '^umask =' 
    line: 'umask = 002'
    state: present

- name: Adding specific RCM user and restricted shell
  user: 
    name: '{{ item.login_name }}' 
    state: present 
    comment: "{{ item.full_name }}"
    groups: rsshusers, apache
    append: True
    shell: /bin/rssh
  with_items: "{{ lookaside_ssh_users }}"
  when: lookaside_ssh_users is defined
  
- name: Importing local users ssh pub keys
  authorized_key: 
    user: '{{ item.0.login_name }}' 
    key: "{{ item.1 }}"
  with_subelements: 
    - '{{ lookaside_ssh_users }}'
    - ssh_pub_key
  when: lookaside_ssh_users is defined


- name: Ensuring specific RCM user can push to lookaside
  acl:
    entity: "{{ item.login_name }}"
    etype: user
    path: "{{ lookaside_rootpath }}/lookaside"
    permissions: rwx
    recursive: yes
    state: present
  with_items: "{{ lookaside_ssh_users }}"  

- name: Ensuring RCM user will be granted rights on new created repositories
  acl:
    default: yes
    entity:  "{{ item.login_name }}"
    etype: user
    path: "{{ lookaside_rootpath }}/lookaside"
    permissions: rwx
    recursive: yes
    state: present
  with_items: "{{ lookaside_ssh_users }}"

- name: Ensuring apache group can push to lookaside
  acl:
    entity: apache
    etype: group
    path: "{{ lookaside_rootpath }}/lookaside"
    permissions: rwx
    recursive: yes
    state: present

- name: Ensuring apache group will be granted rights on new created repositories
  acl:
    default: yes
    entity:  apache
    etype: group
    path: "{{ lookaside_rootpath }}/lookaside"
    permissions: rwx
    recursive: yes
    state: present
  with_items: "{{ lookaside_ssh_users }}"

- name: install the upload.cgi script
  copy:
    src: "upload.cgi"
    dest: "/var/www/cgi-bin/upload.cgi"
    mode: 0755
    setype: "git_script_exec_t"

- name: install the lookaside configuration file 
  template:
    src: "lookaside.cfg.j2"
    dest: "/etc/lookaside.cfg"
    mode: 0644
