- name: Configuring agent in Zabbix server
  include_role:
    name: zabbix-server
    tasks_from: agent_config
  vars:
    zabbix_templates: "{{ zabbix_pagure_templates }}"
    zabbix_groups: "{{ zabbix_pagure_groups }}"
  delegate_to: "{{ zabbix_api_srv }}"  
  tags:
    - monitoring
  when: zabbix_api_srv is defined


