---
- name: Enabling selinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  with_items: "{{ pagure_sebooleans }}"
  tags:
    - selinux

- name: Distributing custom selinux policy file[s]
  copy:
    src: "selinux/{{ ansible_distribution_major_version }}/{{ item }}"
    dest: "/etc/selinux/centos/{{ item }}"
  with_items:
    - pagure.pp
    - pagure-lookaside.pp
  register: sepolicy  
  tags:
    - selinux

- name: Reloading selinux policy on change
  shell: "/usr/sbin/semodule -u /etc/selinux/centos/{{ item.item }}"
  with_items: "{{ sepolicy.results }}"
  when: item.changed
  no_log: True
  tags:
    - selinux
